add_newline = false
format = '$jobs$directory$git_branch$git_status$aws$character'

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style) '
symbol = ''
[aws.region_aliases]
ap-northeast-1 = 'tokyo'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[git_branch]
format = "[\\($branch\\)]($style) "

