add_newline = false
format = """
$directory$git_branch$git_status$aws$terraform
$jobs$character
"""

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style) '
symbol = ''
[aws.region_aliases]
ap-northeast-1 = 'tokyo'

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[λ](bold red)'

[git_branch]
format = "[\\($branch\\)]($style) "

