alias ls="exa"
alias ll="ls -lhF --icons"

alias nv="nvim"
alias gu="gitui"

alias sts="git status -s"
alias cho="git checkout"
alias crb="git checkout -b"
alias pso="git push origin HEAD"
alias psu="git push -u origin HEAD"
alias po="git pull origin"
alias fe="git fetch"
alias fea="git fetch --all"
alias lg="git log --graph"
alias sths="git stash save"
alias sthp="git stash pop"
alias sthl="git stash list"
alias cmt="git commit"
alias cln="git clone"

alias dc="docker compose"
