-- Generated from palette/futaba.lua; do not edit.
-- Regenerate: nvim --headless -u NONE -i NONE -n -c 'luafile scripts/generate.lua' -c 'qa'
vim.g.colors_name = nil
vim.o.termguicolors = true
vim.o.background = "dark"
vim.cmd('highlight clear')
vim.api.nvim_set_hl(0, "Normal", { fg = "#E6E8DF", bg = "#101713" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#E6E8DF", bg = "#101713" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#E6E8DF", bg = "#16201B" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#E6E8DF", bg = "#16201B" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#E6E8DF", bg = "#16201B" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#294038" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#1D2A23" })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#1D2A23" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#87998F" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#87998F" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "Search", { fg = "#101713", bg = "#E6934A" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#31463D" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#31463D" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#667970" })
vim.api.nvim_set_hl(0, "@comment", { fg = "#667970" })
vim.api.nvim_set_hl(0, "String", { fg = "#A1E66C" })
vim.api.nvim_set_hl(0, "Character", { fg = "#A1E66C" })
vim.api.nvim_set_hl(0, "@string", { fg = "#A1E66C" })
vim.api.nvim_set_hl(0, "@character", { fg = "#A1E66C" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#E6934A" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#F0AB67" })
vim.api.nvim_set_hl(0, "@constant", { fg = "#F0AB67" })
vim.api.nvim_set_hl(0, "Number", { fg = "#E5CE67" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#E5CE67" })
vim.api.nvim_set_hl(0, "@number", { fg = "#E5CE67" })
vim.api.nvim_set_hl(0, "@boolean", { fg = "#E5CE67" })
vim.api.nvim_set_hl(0, "Function", { fg = "#65D6CB" })
vim.api.nvim_set_hl(0, "@function", { fg = "#65D6CB" })
vim.api.nvim_set_hl(0, "@function.call", { fg = "#65D6CB" })
vim.api.nvim_set_hl(0, "@function.method", { fg = "#65D6CB" })
vim.api.nvim_set_hl(0, "@function.method.call", { fg = "#65D6CB" })
vim.api.nvim_set_hl(0, "Type", { fg = "#6FB7D2" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#6FB7D2" })
vim.api.nvim_set_hl(0, "@type", { fg = "#6FB7D2" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#6FB7D2" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#E6E8DF" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#E6E8DF" })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = "#E6E8DF" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#B69AD9" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#B69AD9" })
vim.api.nvim_set_hl(0, "Special", { fg = "#B69AD9" })
vim.api.nvim_set_hl(0, "@attribute", { fg = "#B69AD9" })
vim.api.nvim_set_hl(0, "Error", { fg = "#E9675C" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#E9675C" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#E5CE67" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#65D6CB" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#6FB7D2" })
vim.api.nvim_set_hl(0, "DiagnosticOk", { fg = "#A1E66C" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#A1E66C" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#6FB7D2" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#E9675C" })
vim.g.colors_name = "futaba-dark"
