-- Generated from palette/futaba.lua; do not edit.
-- Regenerate: nvim --headless -u NONE -i NONE -n -c 'luafile scripts/generate.lua' -c 'qa'
vim.g.colors_name = nil
vim.o.termguicolors = true
vim.o.background = "light"
vim.cmd('highlight clear')
vim.api.nvim_set_hl(0, "Normal", { fg = "#26332D", bg = "#F3F1E8" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#26332D", bg = "#F3F1E8" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#26332D", bg = "#E9EADF" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#26332D", bg = "#E9EADF" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#26332D", bg = "#E9EADF" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#D1DDD1" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#DEE5D8" })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#DEE5D8" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#64736B" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#64736B" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "Search", { fg = "#F3F1E8", bg = "#B85F22" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#BCC9BD" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#BCC9BD" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#829087" })
vim.api.nvim_set_hl(0, "@comment", { fg = "#829087" })
vim.api.nvim_set_hl(0, "String", { fg = "#477D2C" })
vim.api.nvim_set_hl(0, "Character", { fg = "#477D2C" })
vim.api.nvim_set_hl(0, "@string", { fg = "#477D2C" })
vim.api.nvim_set_hl(0, "@character", { fg = "#477D2C" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#B85F22" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#D3742D" })
vim.api.nvim_set_hl(0, "@constant", { fg = "#D3742D" })
vim.api.nvim_set_hl(0, "Number", { fg = "#9A7B16" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#9A7B16" })
vim.api.nvim_set_hl(0, "@number", { fg = "#9A7B16" })
vim.api.nvim_set_hl(0, "@boolean", { fg = "#9A7B16" })
vim.api.nvim_set_hl(0, "Function", { fg = "#16867F" })
vim.api.nvim_set_hl(0, "@function", { fg = "#16867F" })
vim.api.nvim_set_hl(0, "@function.call", { fg = "#16867F" })
vim.api.nvim_set_hl(0, "@function.method", { fg = "#16867F" })
vim.api.nvim_set_hl(0, "@function.method.call", { fg = "#16867F" })
vim.api.nvim_set_hl(0, "Type", { fg = "#317D9B" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#317D9B" })
vim.api.nvim_set_hl(0, "@type", { fg = "#317D9B" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#317D9B" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#26332D" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#26332D" })
vim.api.nvim_set_hl(0, "@variable.parameter", { fg = "#26332D" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#79599D" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#79599D" })
vim.api.nvim_set_hl(0, "Special", { fg = "#79599D" })
vim.api.nvim_set_hl(0, "@attribute", { fg = "#79599D" })
vim.api.nvim_set_hl(0, "Error", { fg = "#B8463D" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#B8463D" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#9A7B16" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#16867F" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#317D9B" })
vim.api.nvim_set_hl(0, "DiagnosticOk", { fg = "#477D2C" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#477D2C" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#317D9B" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#B8463D" })
vim.g.colors_name = "futaba-light"
